baseurl = "http://blog.sgmansfield.com/"
title = "Scott Mansfield"
languageCode = "en-us"
disqusShortname = "sgmansfield"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Scott Mansfield"

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true
    
    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    #theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "hybrid"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "while(!(succeed = try()))"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Home"

    # Metadata used to drive integrations.
    #googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "UA-27486202-1"
    #gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/ScottMansfield"
    bitbucket = ""
    stackOverflow = "http://stackoverflow.com/users/92602/scott-m"
    linkedin = "https://www.linkedin.com/in/scottgmansfield"
    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/sgmansfield"
    youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    #flattr = ""  # populate with your flattr uid
